// @flow
const path = require('path')
const minify = require('html-minifier').minify

const TemplateCache = require('../lib/TemplateCache')
const compileContent = require('../utils/compileContent')

const buildPageHTML = async (
  data: Object,
  ctx: Object
): Promise<string | void> => {
  const { page } = data
  const { paths, config } = ctx
  let html = compileContent(data)

  if (page.layout !== null) {
    const layoutPath = path.join(paths.layouts, `${page.layout}.html`)
    const template = await TemplateCache.get(layoutPath)

    html = template({
      content: html,
      ...data
    })
  }

  const baseLayoutPath = path.join(paths.layouts, '_base.html')
  const baseTemplate = await TemplateCache.get(baseLayoutPath)

  html = baseTemplate({
    content: html,
    ...data
  })

  if (config.minifyContent) {
    return minify(html, {
      collapseBooleanAttributes: true,
      collapseWhitespace: true,
      decodeEntities: true,
      includeAutoGeneratedTags: false,
      minifyCSS: true,
      minifyJS: true,
      processConditionalComments: true,
      removeEmptyAttributes: true,
      removeEmptyElements: true,
      removeRedundantAttributes: true,
      removeScriptTypeAttributes: true,
      removeStyleLinkTypeAttributes: true,
      sortAttributes: true,
      sortClassName: true,
      trimCustomFragments: true,
      useShortDoctype: true
    })
  }

  return html
}

module.exports = buildPageHTML
