// @flow
const handlebars = require('handlebars')
const path = require('path')
const fs = require('fs-extra')
const marked = require('marked')
const minify = require('html-minifier').minify

const logError = require('./logError')
const info = require('./output/info')
const error = require('./output/error')
const exit = require('./exit')

const renderContent = async (
  content: string,
  data: Object,
  layoutFolderPath: string,
  minifyContent: boolean = true
): Promise<string | void> => {
  const layoutPath = path.join(layoutFolderPath, `${data.page.layout}.html`)

  try {
    const layout = await fs.readFile(layoutPath)

    const template = handlebars.compile(layout.toString())
    const contentHtml = marked(content, {
      highlight: function(code) {
        return require('highlight.js').highlightAuto(code).value
      }
    })

    const html = template({
      content: contentHtml,
      ...data
    })

    if (minifyContent) {
      return minify(html, {
        collapseBooleanAttributes: true,
        collapseWhitespace: true,
        decodeEntities: true,
        includeAutoGeneratedTags: false,
        minifyCSS: true,
        minifyJS: true,
        processConditionalComments: true,
        removeEmptyAttributes: true,
        removeEmptyElements: true,
        removeRedundantAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true,
        sortAttributes: true,
        sortClassName: true,
        trimCustomFragments: true,
        useShortDoctype: true
      })
    }

    return html
  } catch (err) {
    if (err.code === 'ENOENT') {
      error(`Layout "${data.page.layout}" could not be found.`)
      info(data.page.srcFile)
      exit(1)
    }

    logError(err)
  }
}

module.exports = renderContent
